import { useState } from "react";
import { Calendar, MapPin, Download, Star, Clock } from "lucide-react";

// Simple in-memory storage for demo
let plannedTrips = [
  {
    id: 1,
    destination: "Paris, France",
    dates: "June 15-22, 2024",
    duration: "7 days",
    type: "AI Generated", 
    details: "Romantic getaway featuring the Eiffel Tower, Louvre Museum, Seine River cruise, and charming Montmartre district.",
    rating: 4.8
  },
  {
    id: 2,
    destination: "Tokyo, Japan",
    dates: "September 10-20, 2024", 
    duration: "10 days",
    type: "AI Customized",
    details: "Cultural immersion with visits to traditional temples, modern districts like Shibuya, authentic ramen tours, and cherry blossom spots.",
    rating: 4.9
  }
];

export function addPlannedTrip(trip) {
  const newTrip = {
    id: plannedTrips.length + 1,
    ...trip
  };
  plannedTrips.push(newTrip);
}

export default function PlannedTripsSection() {
  const [trips] = useState(plannedTrips);

  const downloadTrip = (trip) => {
    const content = `
TRAVEL PLAN: ${trip.destination}
Generated by TravelAI

Dates: ${trip.dates}
Duration: ${trip.duration}
Type: ${trip.type}
Rating: ${trip.rating}/5 stars

DETAILS:
${trip.details}

ITINERARY HIGHLIGHTS:
- AI-curated local experiences
- Personalized recommendations
- Real-time travel updates
- 24/7 AI assistant support

Generated on: ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${trip.destination.replace(/[^a-zA-Z0-9]/g, '_')}_travel_plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <section id="trips" className="py-16 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            My Planned Trips
          </h2>
          <p className="text-xl text-gray-600">
            Your AI-generated travel plans and itineraries
          </p>
        </div>

        {trips.length === 0 ? (
          <div className="text-center py-12">
            <MapPin className="h-16 w-16 text-gray-400 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-gray-900 mb-2">
              No trips planned yet
            </h3>
            <p className="text-gray-600 mb-6">
              Start chatting with our AI assistant to create your first personalized travel plan!
            </p>
            <button
              onClick={() => {
                const chatButton = document.querySelector('[data-chat-trigger]');
                if (chatButton) chatButton.click();
              }}
              className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors"
            >
              Plan Your First Trip
            </button>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {trips.map((trip) => (
              <div key={trip.id} className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-1">
                      {trip.destination}
                    </h3>
                    <div className="flex items-center text-sm text-gray-600 space-x-4">
                      <div className="flex items-center space-x-1">
                        <Calendar className="h-4 w-4" />
                        <span>{trip.dates}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center space-x-1">
                    <Star className="h-4 w-4 text-yellow-400 fill-current" />
                    <span className="text-sm font-semibold">{trip.rating}</span>
                  </div>
                </div>

                <div className="mb-4">
                  <div className="flex items-center space-x-4 text-sm text-gray-600 mb-3">
                    <div className="flex items-center space-x-1">
                      <Clock className="h-4 w-4" />
                      <span>{trip.duration}</span>
                    </div>
                    <span className="bg-blue-100 text-blue-800 px-2 py-1 rounded-full text-xs font-semibold">
                      {trip.type}
                    </span>
                  </div>
                  <p className="text-gray-700 text-sm line-clamp-3">
                    {trip.details}
                  </p>
                </div>

                <div className="flex space-x-2">
                  <button
                    onClick={() => downloadTrip(trip)}
                    className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center space-x-2"
                  >
                    <Download className="h-4 w-4" />
                    <span>Download Plan</span>
                  </button>
                  <button
                    onClick={() => {
                      const chatButton = document.querySelector('[data-chat-trigger]');
                      if (chatButton) chatButton.click();
                    }}
                    className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
                  >
                    Modify
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}