import { useState, useEffect } from "react";
import { Download, Calendar, MapPin, Clock, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

interface PlannedTrip {
  id: string;
  destination: string;
  dates: string;
  duration: string;
  type: string;
  details: string;
  createdAt: Date;
  rating: number;
}

export default function PlannedTripsSection() {
  const [plannedTrips, setPlannedTrips] = useState<PlannedTrip[]>([]);

  useEffect(() => {
    const savedTrips = localStorage.getItem('plannedTrips');
    if (savedTrips) {
      setPlannedTrips(JSON.parse(savedTrips));
    }
  }, []);

  const downloadTrip = (trip: PlannedTrip) => {
    const content = `
TRAVEL PLAN: ${trip.destination}
Generated by TravelAI

Destination: ${trip.destination}
Travel Dates: ${trip.dates}
Duration: ${trip.duration}
Trip Type: ${trip.type}
Rating: ${trip.rating}/5 stars

DETAILED ITINERARY:
${trip.details}

Powered by TravelAI - Your Intelligent Travel Companion

---
Visit our website for more AI-powered travel recommendations!
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TravelAI-${trip.destination.replace(/[^a-zA-Z0-9]/g, '-')}-Plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAllTrips = () => {
    if (plannedTrips.length === 0) return;

    const content = `
TRAVEL PLANS COLLECTION
Generated by TravelAI

${plannedTrips.map((trip, index) => `
TRIP ${index + 1}: ${trip.destination}
Travel Dates: ${trip.dates}
Duration: ${trip.duration}
Type: ${trip.type}
Rating: ${trip.rating}/5 stars

${trip.details}

---
`).join('\n')}

Generated on: ${new Date().toLocaleDateString()}
Total Trips: ${plannedTrips.length}
Powered by TravelAI - Your Intelligent Travel Companion
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TravelAI-All-Travel-Plans-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (plannedTrips.length === 0) {
    return (
      <section id="planned-trips" className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">My Planned Trips</h2>
            <p className="text-xl text-gray-600 mb-8">Your AI-generated travel plans will appear here</p>
            <div className="bg-gray-50 rounded-2xl p-12 max-w-md mx-auto">
              <MapPin className="w-16 h-16 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-gray-700 mb-2">No trips planned yet</h3>
              <p className="text-gray-500 mb-6">Start chatting with our AI to create your first travel plan!</p>
              <Button 
                onClick={() => {
                  const chatButton = document.querySelector('[data-chat-trigger]') as HTMLButtonElement;
                  if (chatButton) chatButton.click();
                }}
                className="bg-blue-600 hover:bg-blue-700 text-white"
              >
                Plan Your First Trip
              </Button>
            </div>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="planned-trips" className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between mb-12">
          <div>
            <h2 className="text-4xl font-bold text-gray-900 mb-4">My Planned Trips</h2>
            <p className="text-xl text-gray-600">Your personalized AI-generated travel plans</p>
          </div>
          <Button 
            onClick={downloadAllTrips}
            className="bg-green-600 hover:bg-green-700 text-white"
          >
            <Download className="w-4 h-4 mr-2" />
            Download All Plans
          </Button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {plannedTrips.map((trip) => (
            <Card key={trip.id} className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <h3 className="text-xl font-semibold text-gray-900">{trip.destination}</h3>
                    <div className="flex items-center mt-2 text-amber-500">
                      {[...Array(5)].map((_, i) => (
                        <Star key={i} className={`w-4 h-4 ${i < trip.rating ? 'fill-current' : ''}`} />
                      ))}
                      <span className="ml-2 text-gray-600">{trip.rating}/5</span>
                    </div>
                  </div>
                  <Button 
                    onClick={() => downloadTrip(trip)}
                    variant="outline" 
                    size="sm"
                  >
                    <Download className="w-4 h-4" />
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center text-gray-600">
                    <Calendar className="w-4 h-4 mr-2" />
                    <span className="text-sm">{trip.dates}</span>
                  </div>
                  <div className="flex items-center text-gray-600">
                    <Clock className="w-4 h-4 mr-2" />
                    <span className="text-sm">{trip.duration}</span>
                  </div>
                  <div className="bg-blue-50 px-3 py-1 rounded-full inline-block">
                    <span className="text-xs font-medium text-blue-700">{trip.type}</span>
                  </div>
                  <p className="text-gray-600 text-sm line-clamp-3">{trip.details}</p>
                  <div className="text-xs text-gray-400">
                    Created: {new Date(trip.createdAt).toLocaleDateString()}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}

// Helper function to add a new planned trip
export const addPlannedTrip = (tripData: {
  destination: string;
  dates: string;
  duration: string;
  type: string;
  details: string;
  rating: number;
}) => {
  const newTrip: PlannedTrip = {
    id: Math.random().toString(36).substr(2, 9),
    ...tripData,
    createdAt: new Date()
  };

  const savedTrips = localStorage.getItem('plannedTrips');
  const trips = savedTrips ? JSON.parse(savedTrips) : [];
  trips.unshift(newTrip); // Add to beginning
  localStorage.setItem('plannedTrips', JSON.stringify(trips));
  
  // Trigger a custom event to update the UI
  window.dispatchEvent(new CustomEvent('tripAdded'));
  return newTrip;
};